# Generated by Django 5.2.14 on 2026-06-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary earned per working day.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
