# Generated by Django 5.2.14 on 2026-06-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_userpreference_per_day_salary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlySummary',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.userpreference'),
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='attendance.userpreference'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(help_text='The day this record is for.'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
